Repository FeatureBaseDB/featurebase, pull requests merged in 2019-07, with the labels that each got.

#2024 Unmarshal3
  field.go
  fragment.go
  fragment_internal_test.go
  holder.go
  index.go
  roaring/btree.go
  roaring/containers_btree.go
  roaring/containers_slice.go
  roaring/fuzz_test.go
  roaring/roaring.go
  view.go
Labels: changelog.performance

#2029 add ability to disable tracing and use nopTracer
  cmd/server.go
  ctl/server.go
  docs/configuration.md
Labels: changelog.added

#2041 Uip time only
  executor.go
  executor_test.go
  row.go
Labels: changelog.performance

#2048 Add a worker pool for importRoaring jobs
  api.go
  server/config.go
  server/server.go
Labels: changelog.performance

#2050 Default BSI base value to min, max, or 0 depending on the min/max range
  field.go
  field_internal_test.go
Labels: changelog.fixed
