Repository FeatureBaseDB/featurebase, pull requests merged in 2019-05, with the labels that each got.

#1964 Backport #1951
  field.go
  holder.go
  index.go
  server.go
  server_internal_test.go
  view.go
Labels: changelog.fixed

#1939 Extra tracing
  api.go
  field.go
  fragment.go
  fragment_internal_test.go
  go.mod
  go.sum
  http/handler.go
Labels: changelog.added

#1966 simplify contributing instructions by removing weird upstream thing
  CONTRIBUTING.md
Labels: changelog.changed

#1954 TranslateFile - reopen the same instance
  go.mod
  go.sum
  translate.go
  translate_test.go
Labels: changelog.fixed

#1970 Fix filter calls in GroupBy not being translated
  api.go
  executor.go
  executor_test.go
  go.sum
Labels: changelog.fixed

#1973 Fixed error message returned by regex on field and index names
  docs/getting-started.md
  docs/query-language.md
  go.sum
  pilosa.go
Labels: changelog.fixed

#1975 Fixed out of bounds panic to show error
  pql/ast.go
  pql/parser.go
  pql/pqlpeg_test.go
Labels: changelog.fixed

#1902 Unbounded BSI w/ sign magnitude
  api_test.go
  docs/data-model.md
  encoding/proto/proto.go
  executor.go
  executor_test.go
  field.go
  field_internal_test.go
  field_test.go
  fragment.go
  fragment_internal_test.go
  http/client_test.go
  http/handler.go
  index_test.go
  internal/private.pb.go
  internal/private.proto
  internal/public.pb.go
  roaring/roaring.go
  row.go
  view.go
Labels: changelog.added

#1974 WIP: Improve row cache (mostly by not doing it)
  cache.go
  enterprise/b/btree.go
  enterprise/b/containers_btree.go
  enterprise/enterprise.go
  fragment.go
  fragment_internal_test.go
  roaring/btree.go
  roaring/btree_test.go
  roaring/container_stash.go
  roaring/containers_btree.go
  roaring/containers_slice.go
  roaring/containers_test.go
  roaring/roaring.go
  roaring/roaring_helpers_test.go
  roaring/roaring_internal_test.go
  roaring/roaring_test.go
  row.go
Labels: changelog.performance

#1986 fixed swapped order of flags and file version bytes on unmarshal
  fragment_internal_test.go
  roaring/roaring.go
Labels: changelog.none
