Repository FeatureBaseDB/featurebase, pull requests merged in 2019-09, with the labels that each got.

#2054 Minor fixes to query language docs
  docs/query-language.md
Labels: changelog.none

#2064 Update CirleCI build with Go 1.13 and run enterprise tests
  .circleci/config.yml
  go.mod
  roaring/unmarshal_binary.go
Labels: changelog.changed

#2067 2066 create field race
  server.go
  server/server_test.go
Labels: changelog.fixed

#2068 Add support for TLS client certificate verification and custom CA
  cmd/export.go
  cmd/import.go
  ctl/common.go
  ctl/server.go
  docs/configuration.md
  docs/tutorials.md
  http/translator.go
  server/config.go
  server/server.go
Labels: changelog.added
