Repository FeatureBaseDB/featurebase, pull requests merged in 2019-06, with the labels that each got.

#1990 use os.Rename semantically correctly
  view.go
Labels: changelog.none

#1993 False Positive nodeLeave events put cluster in an unusable state (Starting)
  cluster.go
  cluster_internal_test.go
  internal/clustertests/cluster_test.go
Labels: changelog.changed

#1992 Add Prometheus stats backend
  docs/administration.md
  docs/configuration.md
  go.mod
  go.sum
  http/handler.go
  prometheus/prometheus.go
  server/server.go
Labels: changelog.added

#1987 Allow partial translate file reads.
  http/handler.go
  translate.go
  translate_test.go
Labels: changelog.fixed

#1994 Add Prometheus tests, refactor http stats as middleware, minor fixes
  go.mod
  http/handler.go
  prometheus/prometheus.go
  prometheus/prometheus_test.go
Labels: changelog.changed, observability

#1996 Remove extraneous stat tags to improve prometheus performance
  api.go
  field.go
  index.go
  stats/stats_test.go
  view.go
Labels: changelog.removed, observability

#2001 Update Alpine to 3.9.4 in Dockerfile
  Dockerfile
Labels: changelog.changed

#2003 Backport #2001
  Dockerfile
Labels: changelog.changed

#2002 Backport #2001
  Dockerfile
Labels: changelog.changed

#1983 Add MinRow and MaxRow calls
  executor.go
  executor_test.go
  fragment.go
  roaring/containers_test.go
  roaring/roaring.go
  roaring/roaring_test.go
Labels: changelog.added

#2004 Added fuzzing code and readme.md to explain the fuzzer
  roaring/README.md
  roaring/fuzzer.go
Labels: changelog.added

#2019 Fix various container iteration bugs in Roaring
  roaring/roaring.go
  roaring/roaring_internal_test.go
  roaring/roaring_test.go
Labels: changelog.fixed

#2021 Malformed Offset Bug in readOffsets and readWithRuns
  roaring/fuzz_test.go
  roaring/roaring.go
Labels: changelog.fixed

#2023 Add naive implementations of Roaring and fuzz test
  roaring/fuzzer.go
  roaring/naive.go
  roaring/naive_test.go
  roaring/roaring.go
  roaring/roaring_nop_sentinel.go
  roaring/roaring_sentinel.go
Labels: changelog.added

#2016 Test for no containers
  roaring/roaring_internal_test.go
Labels: changelog.added
